gantt
    dateFormat YYYY-MM-DD
    axisFormat %Y%b%d
    section Design
    Start of F21 :milestone, F21, 2021-09-01, 1d
    Idea/Problem Brainstorming :a1, 2021-09-07, 1w
    Problem Definition  :a2, after a1, 1w
    Concept Solutions  :a3, after a2, 1w
    Design Selection  :a4, after a3, 1w
    Reading Week  :rw, after a4, 1w
    Patent Review  :a5, after rw, 1w
    PDP :milestone, PDP, 2021-11-02, 1d
    Detailed Design Refinement  :a8, after PDP, 2w
    FDP :milestone, FDP, 2021-11-30, 1d
    F21 Final Report :milestone, f21fr, 2021-12-07, 1d

    section Build
    Start of W22  :milestone, W22, 2022-01-05, 1d
    Final Report :milestone, 2022-04-10, 1d
    Verification & Integration:it, 2022-02-26, 2022-03-18
    Demo :milestone, 2022-03-09, 1d
    Symposium :milestone, symposium, 2022-03-18, 1d

    section Mechanical
    Design :mechdesign, after a8, 9w
    Manufacture :mech, after mechdesign, 2022-03-01
    Assembly :mechassm, 2022-03-01, 3d
    Testing & Iteration :after mechassm, 2022-03-18

    section Electrical
    Controller Research :elecselec, after a8, 3w
    Custom Design Research:elecdesign, after W22, 2022-02-05
    Block Diagram & Schematic Layout :elecdiag, after elecdesign, 2022-02-19
    PCB Layout :elecpcb, after elecdiag, 2022-02-26
    PCB Shipping :elecship, after elecpcb, 2022-03-12
    Testing & Integration :elec, after elecship, 2022-03-18

    section Software
    Open-Source Software Architecture Review :softreview, after a8, 4w
    Slicer :slicer, after W22, 2022-03-12
    Firmware :fw, after W22, 2022-03-18
    Integration :sw, 2022-03-04, 2022-03-18
